0.5.2 optimization
Onestop-Agrotech/Seva-Consumer pull request #88
Opened 2020-10-03 06:21 UTC by vikasprashar99

Optimized code for following: -

1. rendercarticon
2. add, remove helper function

@Rahul-Vijay and @Rajat012k Please look for any issues/bugs and merge if not.

2020-10-03 23:16 UTC, Rahul-Vijay commented on lib/screens/common/animatedCard.dart
> +  //   addToCart
We can remove the comments.?

2020-10-03 23:16 UTC, Rahul-Vijay commented on lib/screens/common/common_functions.dart
> +  static void helper(
how can we make this generic.? What I mean is, currently we have hard-coded all the `quantity metrics`, we should make it dynamic ? We can have a generic class ?

2020-10-03 23:16 UTC, Rahul-Vijay commented on lib/screens/productsNew/details.dart
> +  //   if (widget.p.details[0].quantity.allowedQuantities[index].metric == "Kg") {
we can remove all the comments here

2020-10-03 23:45 UTC, Rahul-Vijay requested changes
- There is a bug. Steps to reproduce - 
Go to mainLanding page and add one of the bestsellers. Close the page, then go to some other page. Then come back and re-open the added bestseller and try to add or subtract, it doesn't work. 
There is no error in console.

2020-10-04 03:45 UTC, vikasprashar99 commented
> - There is a bug. Steps to reproduce - 
> Go to mainLanding page and add one of the bestsellers. Close the page, then go to some other page. Then come back and re-open the added bestseller and try to add or subtract, it doesn't work. 
> There is no error in console. 

This was the issue I was taking of , it was before also.

2020-10-04 07:04 UTC, Rahul-Vijay commented
> > * There is a bug. Steps to reproduce -
> >   Go to mainLanding page and add one of the bestsellers. Close the page, then go to some other page. Then come back and re-open the added bestseller and try to add or subtract, it doesn't work.
> >   There is no error in console.
> 
> This was the issue I was talking of , it was before also.

Check #90 , you can fix that bug in this PR itself

2020-10-07 15:32 UTC, Rahul-Vijay commented
re work this PR @Rajat012k & @vikasprashar99, pull from 0.5.2 and resolve conflicts.

2020-10-08 04:29 UTC, Rahul-Vijay approved these changes

2020-10-08 04:29 UTC, merged